name: Databricks CI/CD with Personal Access Token

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      # Default to production if not set
      DEPLOY_ENV: prd

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          # Set the environment (default is 'prd')
          if [ -f "./env.txt" ]; then
            export DEPLOY_ENV=$(cat ./env.txt)
          fi
          echo "Deploying to environment: $DEPLOY_ENV"

          if [ "$DEPLOY_ENV" = "prd" ]; then
            echo "DATABRICKS_HOST=https://adb-3589910424805442.2.azuredatabricks.net" >> $GITHUB_ENV
            echo "DATABRICKS_TOKEN=dapi8882cb3a92b6578dcaf515101c03324f-2" >> $GITHUB_ENV
          else
            echo "DATABRICKS_HOST=<UAT_DATABRICKS_URL>" >> $GITHUB_ENV
            echo "DATABRICKS_TOKEN=<UAT_PERSONAL_ACCESS_TOKEN>" >> $GITHUB_ENV
          fi

      - name: Install Databricks CLI
        uses: microsoft/install-databricks-cli@v1.0.0

      - name: Import Notebooks to Databricks
        uses: microsoft/databricks-import-notebook@v1.0.0
        with:
          databricks-host: ${{ env.DATABRICKS_HOST }}
          databricks-token: ${{ env.DATABRICKS_TOKEN }}
          local-path: ./notebooks  # Adjust based on your repo structure
          remote-path: /Workspace/Users/22130035@student.hcmus.edu.vn
